export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAILURE = 'GET_TEAMS_FAILURE';

export const ADD_EVENTS_SUCCESS = 'ADD_EVENTS_SUCCESS';
export const ADD_EVENTS_FAILURE = 'ADD_EVENTS_FAILURE';

export const APP_USER_SUCCESS = 'APP_USER_SUCCESS';

